[package]
name = "string_art"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
rand = "0.8"
ndarray = "0.15.6"
imageproc = "0.23.0"
plotters = "0.3"
